### ISSUE TITLE
IP adress is none

### ISSUE THREAD

**Issue by narminGhaffari** [alishibli97/image-caption-scraper#1]
Hi, Do you have any idea what can cause this problem?
![image](https://github.com/alishibli97/image-caption-scraper/assets/64002842/aa18b190-4381-4f24-8667-81804135aa7e)

**Comment by alishibli97** [comment]
@narminGhaffari 
Update: I have modified the implementation to fetch the public IP address from a new more reliable source. This change should resolve the issue previously reported. Please test with the updated code and confirm if the issue is resolved on your end. Your feedback would be greatly appreciated to ensure the fix is effective.

**Comment by chandra-prakash-94** [comment]
![image](https://github.com/alishibli97/image-caption-scraper/assets/29017226/8ca5e9c8-1f27-424e-b389-dff5d4787ffa)
@alishibli97 I am still facing this issue. Kindly suggest what can be done.
